apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: farm-monitoring
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "admin"
  RABBITMQ_DEFAULT_PASS: "changeme_in_production"
  RABBITMQ_USERNAME: "admin"
  RABBITMQ_PASSWORD: "changeme_in_production"
